### ISSUE TITLE
лайтбокс: переключение между несколькими картинками

### ISSUE THREAD

**Issue by indeyets** [davidmz/friendfeed-and-co#10]
Вот, например, пост: https://friendfeed.com/bylin/10057781

После клика на одну из картинок хочется переключится на соседнюю. В идеале:
1. Управление стрелочками с клавиатуры (vim-режим для фанатов)
2. Полупрозрачные картинки-кнопки для клика мышью

**Comment by davidmz** [comment]
Да, мне этого тоже всё время хочется, но никак не соберусь сделать)

**Comment by davidmz** [comment]
Сделал в 1.45 (https://github.com/davidmz/friendfeed-and-co/commit/d60ed060354cd33aebe7ab764c953f21bab76f63). Было непросто)
