### ISSUE TITLE
Лайтбокс в Safari открывается в левом верхнем углу, а не по центру

### ISSUE THREAD

**Issue by f355** [davidmz/friendfeed-and-co#11]
Путем экспериментов в инспекторе выяснено, что это лечится установкой `display: -webkit-flex;` на `.light-box-container`, но уверенности в том, что это не поломает что-нибудь в других браузерах, у меня нет.

**Comment by davidmz** [comment]
Спасибо! У меня нет Сафари, так что тестировать в нём не могу. Но в нём да, весь флекс с префиксами.

Исправил в v1.44 (0cecda6420f3ae85482d531473ba37e9c4e58eca)
