### ISSUE TITLE
Виджеты, когда автоматика не сработала (Youtube, …)

### ISSUE THREAD

**Issue by indeyets** [davidmz/friendfeed-and-co#8]
Вот тут, например https://friendfeed.com/indeyets/3f91e92a/blur-magic-whip-go-out
ссылка на youtube есть, а плеера нет. А мог бы быть :)

Или вот: https://friendfeed.com/indeyets/924bcdbe плеер для аудио мог бы быть

**Comment by davidmz** [comment]
Тут ещё более интересная вещь обнаружилась: ютуб-виджеты не работают, если FrF загружен по HTTPS: https://friendfeed.com/indeyets/e5fa0346/j-bach-sonata-for-violin-and-clavier-in-b-minor

Ок, всё хорошо, но чем играть .m4a?:)

**Comment by indeyets** [comment]
а родной френдфидовский плеер не потянет m4a? я почему-то думал, что он сумеет. но не проверял :)

**Comment by indeyets** [comment]
виджеты видимо не работают из-за того что код пытается грузиться по http?

**Comment by davidmz** [comment]
Да, FrF вообще не очень в курсе, что он умеет HTTPS:) Поэтому юзерпики он всё равно грузит через HTTP, и ютубовские ифреймы пытается тоже. Но ифреймы уже браузер не позволяет.

Вообще, с ютубом просто — есть такой сервис embed.ly, он делает довольно симпатичные виджеты из произвольных урлов. Можно проверять, если в посте есть ссылка и FrF её не обработал сам — вставлять превью от embed.ly.

Всё веб-плееры, по-моему, умеют только mp3. Хотя [вот тут](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility) пишут ещё про “AAC in MP4”. Это оно?

**Comment by indeyets** [comment]
> Хотя вот тут пишут ещё про “AAC in MP4”. Это оно?

оно

**Comment by davidmz** [comment]
В общем, с аудио надо экспериментировать. Предвижу проблемы со всем, что не mp3)

Для mp3, кстати, френдфид плеер показывает: https://friendfeed.com/davidmz/fd1066d2/mp3

**Comment by indeyets** [comment]
показывает, но потом говорит file-not-found (по крайней мере у меня, на https) :)
на http даже работает. ну и вот я почему-то думал что этот же плеер и m4a потянет

**Comment by davidmz** [comment]
Ну, ютуб теперь показывается, а заодно и vimeo (которое вообще как видео не воспринималось). С не-mp3-аудио я всё-таки пока возиться побоялся)

**Comment by indeyets** [comment]
спасибо! работает :)
